# Generated by Django 4.1.6 on 2023-03-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contectus',
            name='username',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
