# Generated by Django 4.1.6 on 2023-04-03 13:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_contectus_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('username', models.CharField(max_length=222)),
            ],
        ),
        migrations.RemoveField(
            model_name='contectus',
            name='username',
        ),
    ]
