# Generated by Django 4.1.6 on 2023-04-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_profile_remove_contectus_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
