# Generated by Django 4.1.6 on 2023-04-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_addimage_addnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addnew',
        ),
    ]
