# Generated by Django 4.1.6 on 2023-04-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_delete_addnew'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addimage',
            new_name='maddimage',
        ),
    ]
