# Generated by Django 4.1.6 on 2023-04-21 06:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_rename_addimage_maddimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='aaddimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('desc', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='laddimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('desc', models.CharField(max_length=222)),
            ],
        ),
    ]
