# Generated by Django 4.1.6 on 2023-04-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_aaddimage_laddimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
            ],
        ),
        migrations.DeleteModel(
            name='laddimage',
        ),
        migrations.DeleteModel(
            name='maddimage',
        ),
        migrations.AddField(
            model_name='aaddimage',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web_app.name'),
        ),
    ]
