# Generated by Django 4.1.6 on 2023-04-28 08:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_name_delete_laddimage_delete_maddimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='laddimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('desc', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='maddimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('desc', models.CharField(max_length=222)),
            ],
        ),
        migrations.RemoveField(
            model_name='aaddimage',
            name='name',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
