# Generated by Django 4.1.6 on 2023-05-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_laddimage_maddimage_remove_aaddimage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaddimage',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laddimage',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maddimage',
            name='desc',
            field=models.TextField(),
        ),
    ]
